config/routes.rb
Rails.application.routes.draw do

  resources :like_tweets

  resources :relationships

  resources :tweets, :except => :index 

  resources :users

  root to: 'users#login'
  match ':controller/:action', :via => [:get, :post]
  
  match "/auth/google_oauth2/callback" => "sessions#create", via: [:get, :post]
  
  get 'user/logout', :to => "users#logout"
  get 'tweet_index', :to => "tweets#user_tweet"
  get 'like_tweet', :to => "tweets#like_tweet"
  post 'like', :to => "like_tweets#like_tweet"
  post 'unlike', :to => "like_tweets#unlike"
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :tweet
	
end

app/models/like_tweet.rb
class LikeTweet < ActiveRecord::Base

	belongs_to :user
	belongs_to :tweet
	belongs_to :liked_tweets, class_name: 'Tweet', foreign_key: 'tweet_id'

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	
	belongs_to :followeds, class_name: 'User', foreign_key: "followed_id"
	belongs_to :followers, class_name: 'User', foreign_key: "follower_id"
	
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	
	belongs_to :user

	has_many :comments, class_name: 'Tweet', foreign_key: 'parent_id'

	validates :user_id, presence: true
	validates :content, presence: true, length: { maximum: 140 }

end

app/models/user.rb
class User < ActiveRecord::Base
	
	# has_secure_password

	has_many :tweets, -> { where parent_id: nil}
	has_many :like_tweets
	has_many :liked_tweets, through: :like_tweets
	

	has_many :followed_relationships, class_name: "Relationship", foreign_key: "follower_id"
	has_many :follower_relationships, class_name: "Relationship", foreign_key: "followed_id"

	has_many :followeds, through: :followed_relationships
	has_many :followers, through: :follower_relationships

	EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i

	  validates :name, presence: true
		validates :username, uniqueness: true, presence: true
		validates :email, uniqueness: true, presence: true, :format => EMAIL_REGEX
 	# validates :password, length: { minimum: 6 }

	def self.create_with_omniauth(auth)
	  create! do |user|
	    user.provider = auth["provider"]
	    user.uid = auth["uid"]
	    user.name = auth["info"]["name"]
	    user.password = auth["info"]["password"]
	    user.email = auth["info"]["email"]
	    @username = user.name.split(' ').join('.')
	    user.username = @username
	  end
	end

	def self.search(search)
  	condition = "%" + search + "%"
  	where('name LIKE ?', condition)
 	end
  
  def following?(obj)
    self.followeds.include?(obj)
  end

  def already_like?(obj)
    self.liked_tweets.include?(obj)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception  

  def confirm_logged_in
    unless session[:user_id]
      flash[:notice] = "Please log in."
      redirect_to(:controller => 'users', :action => 'login')
      return false #halt the before_action
    else
      return true
    end
  end

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/like_tweets_controller.rb
class LikeTweetsController < ApplicationController

	layout 'front'
	def create
		@like = LikeTweet.new
		@like.user_id = current_user.id
		#@like.tweet_id = 

		if @like.save
			respond_to do |format|
				format.html
				format.js
			end
		else
			flash[:error] = "already Liked"
		end
	end

	def destroy
    @like = LikeTweet.find(params[:id])
    @like.destroy
    redirect_to user_path params[:id]
	end

	def like_tweet
		LikeTweet.create user_id: current_user.id, tweet_id: params[:id]
		redirect_to tweet_index_path
	end

	def unlike
		@like = LikeTweet.find_by_tweet_id(params[:id])
		@like.destroy
		redirect_to tweet_index_path
	end
	
	private
	def liketweet_params
		params.require(:tweetlike).permit(:user_id, :tweet_id)
	end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	
	def create 
	  @relationship = Relationship.new
	  @relationship.followed_id = params[:id]
	  @relationship.follower_id = current_user.id
	 
	  if @relationship.save
	    respond_to do |format|
				format.html { redirect_to @user }
				format.js
			end
	  else
	    flash[:error] = "Couldn't Follow"
	  end
	end

	def destroy
    @relationship = Relationship.find(params[:id])
    @relationship.destroy
    redirect_to user_path params[:id]
	end

	def follow
		@followed = User.find(params[:id])
		current_user.followeds << @followed
		redirect_to user_path current_user.id
		flash[:notice] = "Followed"
	  # Relationship.create follower_id: current_user.id, followed_id: params[:id]
	end

	def unfollow
		@relationship = Relationship.find_by_followed_id(params[:id])
    @relationship.destroy 
    redirect_to user_path current_user.id
    flash[:notice] = "UnFollowed"
	end
	
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def create
  auth = request.env["omniauth.auth"]
  user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
  session[:user_id] = user.id
  redirect_to user, :notice => "Signed in!"
end

def destroy
  session[:user_id] = nil
  redirect_to root_url, :notice => "Signed out!"
end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

	before_action :confirm_logged_in 
	layout 'front'

	def new
	end
	
	def show
		@tweets = Tweet.all #find(params[:id])
		@cnt = @tweets.count
	end

	def create
		@user = current_user
		@tweet = Tweet.new(tweet_params)
		flash[:error] = "Please check your tweet....!!!!" unless @tweet.save
		respond_to do |format|
    	format.js 
    	format.html {redirect_to tweet_index_path }
    end
	end

	def destroy
		@tweet = Tweet.find(params[:id]).destroy
		respond_to do |format|
    		format.js 
    		format.html
    	end
	end

	def user_tweet
		@tweet = Tweet.new
		@user = current_user
		@users = @user.followeds 
		@tweets = []#@user.tweets.order("created_at DESC")
		@users.each do |x|
			@tweets.concat(x.tweets)
		end
		render 'index'
	end

	private

  def tweet_params
    params.require(:tweet).permit(:content, :user_id, :like, :parent_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  layout 'front'
	before_action :confirm_logged_in, :except => [:login, :attempt_login, :logout, :new, :create]
  
	def new
    @user = User.new
	end

	def create
  	@user = User.create(user_params)
   	if @user.save
   		flash[:notice] = "Successfully registerd"
    	redirect_to(:action => 'login')
  	else
    	render 'new'
  	end
	end

	def login
  end

	def attempt_login
		if params[:username].present? && params[:password].present?
      found_user = User.where(:username => params[:username]).first
      if found_user  
          authorized_user = found_user.authenticate(params[:password])
      end  
  	end
    if authorized_user
        session[:user_id] = authorized_user.id
	      session[:username] = authorized_user.username
	      flash[:notice] = "you are now logged in."
	      redirect_to(:action => 'show' , :id => authorized_user.id)
    else
      flash[:notice] = "Invalid Username/Password."
      redirect_to(:action => 'login')
    end
  end

  def show
    @user =User.find(params[:id])
    @tweet = Tweet.new
    @tweets = @user.tweets.order("created_at DESC")
    # @follow = @user.followers.order("created_at")
  end

  def logout
    session[:user_id] = nil
    session[:username] = nil
  	flash[:notice] = "Logged Out"
    redirect_to(:action => "login")
  end

  def search
    @search = User.search(params[:search])
    @user = current_user
  end

  private

  def user_params
    params.require(:users).permit(:name, :username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/like_tweets_helper.rb
module LikeTweetsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/ribbits_helper.rb
module RibbitsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', media: 'all', 'data-turbolinks-track' => true  %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |key, value| %>
  <%= content_tag :div, value, class: "flash #{key}" %>
<% end %>
<%= yield %>

</body>
</html>

app/views/layouts/front.html.erb
<!DOCTYPE html>
<html>
	<head>
  	<title>Twitter</title>
		<%= stylesheet_link_tag('application', :media => 'all') %>
		<%= javascript_include_tag 'application', media: 'all', 'data-turbolinks-track' => true  %>
  	<%= csrf_meta_tags %>
	</head>
	<body>
		<div id = "main">
		<% if !flash[:notice].blank? %>
			<div class="notice">
				<%= flash[:notice]%>
			</div>
		<% end %>
			<div id = "content">
				<%= yield %>
			</div>
		</div>
	</body>
</html>

app/views/tweets/_tweet.html.erb
<div class="tweetWrapper" id="<%= tweet.id%>"><hr>
    @<%= tweet.user.name %><br>
    -->><%= tweet.content %><br>
    <%= time_ago_in_words(tweet.created_at) %>
    <div id = "destweet"> <%= button_to "Delete", tweet, method: 'delete', remote: true %></div>
</div><br>

app/views/tweets/create.js.erb
$("<%= escape_javascript(render partial: 'tweet', locals: {tweet: @tweet}) %>").prependTo("#tweet");

app/views/tweets/destroy.js.erb
$("#<%=@tweet.id%>").remove()

app/views/tweets/index.html.erb
<%= link_to("HOME", {:controller => "users", :action => "show", :id => @user.id}) %>
<div>
  <h1>Public Tweets</h1>
  <% @tweets.each do |tweet| %><hr>
    <div>
      <%= tweet.content %><br>
      <%= tweet.user.name %>
      <%= time_ago_in_words(tweet.created_at) %>
      <% if @user.already_like? tweet %>
      <%= button_to "unlike", unlike_path(:id => tweet.id)%>
      <% else %>
      <%= button_to "like", like_path(:id => tweet.id)%>
      <%end %>
      <%= tweet.comments.count %> Comments
      <br>
      <%= form_for @tweet do |f| %>
        <%= f.text_field :content, placeholder: "Write a comment..." %>
        <%= f.hidden_field :parent_id, :value => tweet.id %>
        <%= f.hidden_field :user_id, :value => @user.id%>
        <%= f.submit "Comment" %>
      <% end %>
      <% tweet.comments.each do |com|%>
        -->> <%= com.content %><br>
        by <%= com.user.name %> <%= time_ago_in_words(com.created_at)%> ago<br>
      <%end%>
      <br>
    </div>
  <% end %>
</div>

app/views/users/login.html.erb
<% @page_title = "User Login" %>

<div class="login">
<h2 id = 'content'>Log In to Twitter</h2>
	<%= form_tag(:action => 'attempt_login') do %>
	<table class = 'login'>
		<tr>
			<td><%= label_tag(:username) %></td>
			<td><%= text_field_tag(:username) %></td>
		</tr >
		<tr>
			<td><%= label_tag(:password) %></td>
			<td><%= password_field_tag(:password) %></td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td><%= submit_tag("Log In") %></td>
		</tr>
	</table>
	<% end %>
<p id = "content"> New User..? <%= link_to("Register Here", new_user_path) %></p>
<%= link_to "Sign in with Google", "/auth/google_oauth2" %>
</div>

app/views/users/new.html.erb
<div class="center">
  <h1>New to Twitter...!!! </h1>
  <h2>Register Here</h2>
  <%= form_for(:users, :url => {:action => 'create'}) do |f|%>
  <table>
    <tr>
      <td><%= label_tag(:name) %></td>
      <td><%= f.text_field :name, placeholder: "name" %></td>
    </tr>
    <tr>
      <td><%= label_tag(:username) %></td>
      <td><%= f.text_field :username, placeholder: "username" %></td>
    </tr>
    <tr>
      <td><%= label_tag(:email) %></td>
      <td><%= f.text_field :email, placeholder: "email" %></td>
    </tr>
    <tr>
      <td><%= label_tag(:password) %></td>
      <td> <%= f.password_field :password, placeholder: "password" %></td>
    </tr>
    <tr>
      <td><%= label_tag(:password_confirmation) %></td>
      <td><%= f.password_field :password_confirmation, placeholder: "password" %></td>
    </tr>
    <tr>
      <td><%= f.submit "Create Account" %></td>
    </tr>
  </table>
  <% end %>
  <%= link_to("Login Here", root_path) %>
  <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  
</div>

app/views/users/search.html.erb
<%= link_to("HOME", {:controller => "users", :action => "show", :id => @user.id}) %>
<div>
<%@search.each do |s|%>	
<h2>User Details</h2>	
<% if @user and s != @user %>
	<% if @user.following? s %>
	<%= button_to "UnFollow", controller: 'relationships', action: "unfollow", :id => s.id %>
	<% else %>
	<%= button_to "Follow", controller: 'relationships', action: "follow", :id => s.id %>
	<% end %>
<% end %>
	<table>
		<tr>
			<td>Name</td>
			<td><%= s.name %></td>
		</tr>
		<tr>
			<td>Email</td>
			<td><%= s.email%></td>
		</tr>
		<tr>
			<td>Username</td>
			<td><%= s.username %></td>
		</tr>
	</table><br>
	<% s.tweets.each do |tweet|%>
		<div class="tweetWrapper">
	  	<p class="time"><%= tweet.content %><br>
	  	<%= time_ago_in_words(tweet.created_at) %></p>
		</div>
	<% end %>
<% end %>
</div>

app/views/users/show.html.erb
<div id="tweets">
  <%= link_to("Logout", user_logout_path) %><br>
  <%= form_tag(:action => 'search', :method => 'get') do %>
    <p>
      <%= text_field_tag :search, "", placeholder: "Enter Name" %>
      <%= submit_tag "Search" %>
    </p>
  <% end %>
  <h1>Your Tweet Profile</h1>
  <div>
      Name: <%= @user.name %><br>
      UserName: @<%= @user.username %><br>
      Email : <%= @user.email %><br>
      <p>
      <li><%= @user.tweets.size %> Tweets</li>
      <li><%= @user.followers.count %> Followers</li>
        <ul>
        <% @user.followers.each do |fol| %>
          <li><%= fol.name %></li>
        <% end %>
        </ul>
      <li><%= @user.followeds.count %> Followings</li>
        <ul>
          <% @user.followeds.each do |fol| %>
            <li><%= fol.name %></li>
          <% end %>
        </ul>
      <h2><%= link_to("Public Tweets", tweet_index_path)%><br></h2>
  </div>
</div>

<div id="createTweet">
  <h2 id = 'createTweet'>Create a Tweet</h2>
    <%= form_for @tweet, remote: true do |f| %>
    <%= f.text_area :content, size: '50x2' %>
    <%= f.hidden_field :user_id, :value => @user.id%><br>
    <%= f.submit "Post Tweet!" %>
    <% end %>
</div>

<div class="left">
<h1>Your Tweets</h1>
  <div id='tweet'>
    <% @tweets.each do |tweet| %>
        <div class="tweetWrapper" id="<%= tweet.id%>"><hr>
          @<%= @user.name %><br>
          -->><%= tweet.content %><br>
          <%= time_ago_in_words(tweet.created_at) %> ago
          <%= button_to "Delete", tweet, method: 'delete', remote: true %>
        </div><br>
    <% end %>
  </div>
</div>